### ISSUE TITLE
Get blank field name on some structures

### ISSUE THREAD

**Issue by Li4n0** [goretk/pygore#14]
The binary I used for test is [bettercap](https://github.com/bettercap/bettercap/releases/download/v2.26.1/bettercap_darwin_amd64_v2.26.1.zip)

I use redress first, and it could analyze it correctly, all struct's filed name is right:
```bash
redress -struct bettercap > bet.txt
```
And then I used pygore, but the result has some struct's field name is blank.

I use this script to find these structs:
```python3
import pygore
f = pygore.GoFile("/tmp/test/bettercap")
types = f.get_types()
for t in types:
    for f in t.fields:
        if f.fieldName == "":
            print("Struct:",t.name)
            print("field:",f.name)
```
![image](https://user-images.githubusercontent.com/34324462/71400632-5866bd00-2662-11ea-821b-ff3c5de72b4d.png)
We can see gore analyze correct but pygore wrong from this image

**Comment by Ch111p** [comment]
After some experiments, I realized that to any structs, if they have same type member, then the member's name are always same or they all blank.So not only blank, sometimes the member's name is wrong. Just like the pictures below show:
![TIM图片20200211165546](https://user-images.githubusercontent.com/32428352/74222438-77dba700-4cef-11ea-861e-346f79e62904.jpg)
Beacuse in redress, the result always right. The source code must be correct, so I think this bug may caused by cgo. Maybe the complex type, like map, don't have a relatively type, so it can not passed directly between Golang and C. But I don't know how to confirm or fix it. 
Hopefully this could be helpful to you guys.

**Comment by TcM1911** [comment]
This is a very strange issue. The cgo code takes the GoString and copying it to the C-heap and creates a Cstring:
```go
ct.fieldName = arena.cstring(t.FieldName)
```
It uses this wrapper function:
```go
func (a *arena) cstring(str string) *C.char {
	cs := C.CString(str)
	*a = append(*a, unsafe.Pointer(cs))
	return cs
}
``
It uses the `CString` function from cgo to create the string and saves the pointer so it can free the memory when the file is closed.

The cgo function just allocates the memory and copying the bytes to the buffer. Lastly it adds a null byte at the end.
```go
const cStringDef = `
func _Cfunc_CString(s string) *_Ctype_char {
	p := _cgo_cmalloc(uint64(len(s)+1))
	pp := (*[1<<30]byte)(p)
	copy(pp[:], s)
	pp[len(s)] = 0
	return (*_Ctype_char)(p)
}
```
I don't see much that could go wrong here unless the GoString has some null bytes in the beginning of the string that Go ignores when it prints it.

**Comment by TcM1911** [comment]
Version 0.4.0, with the fix, has been uploaded to pypi.
